services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: asiayo
    container_name: asiayo
    restart: unless-stopped
    networks:
      - asiayo-network
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
    ports:
      - 8000:8000

networks:
  asiayo-network:
    driver: bridge